apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabby-deployment
  namespace: tab
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: tabby-deployment
  template:
    metadata:
      labels:
        app: tabby-deployment
    spec:
      containers:
        - name: back-end
          image: public.ecr.aws/s3y9k6b7/tabby:latest
          livenessProbe:
            httpGet:
              path: /ping
              port: 8082
            failureThreshold: 1
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /ping
              port: 8082
            failureThreshold: 8
            periodSeconds: 15
          env:
          - name: AWS_ACCESS_KEY_ID
            value: "AKIA5Y57L2I37TQ2AKEA"
          - name: AWS_SECRET_ACCESS_KEY
            value: "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"
          - name: TEST_ENV_VAR
            value: "TEST_ENV_VAR"
          - name: DB_URL
            value: "jdbc:postgresql://tabbydb.c8oyvwlbcggq.us-east-2.rds.amazonaws.com:5432/tabby_db"
          - name: DB_PASSWORD
            value: "Tabby1234"
          - name: DB_USERNAME
            value: "tabbydb"
          - name: REDIS_HOST_URL
            value: "172.105.33.59"
          - name: REDIS_PASSWORD
            value: "865CE0E6-03E4-4B09-9F23-13A64C507E58"
          - name: REDIS_PORT
            value: "6379"
          - name: SERVER_PORT
            value: "8082"
          - name: SCHEDULER_DB_URL
            value: "jdbc:postgresql://tabbydb.c8oyvwlbcggq.us-east-2.rds.amazonaws.com:5432/tabby_scheduler_db"
          - name: SCHEDULER_DB_USERNAME
            value: "tabbydb"
          - name: SCHEDULER_DB_PASSWORD
            value: "Tabby1234"
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
#kubectl autoscale deployment tabby-deployment --cpu-percent=50 --min=2 --max=3 -n tab